package com.footballai.analyzer.util

object LeagueTranslator {

    private val countryMap = mapOf(
        // Európa
        "England" to "Anglia",
        "Spain" to "Spanyolország",
        "Italy" to "Olaszország",
        "Germany" to "Németország",
        "France" to "Franciaország",
        "Hungary" to "Magyarország",
        "Portugal" to "Portugália",
        "Netherlands" to "Hollandia",
        "Belgium" to "Belgium",
        "Turkey" to "Törökország",
        "Poland" to "Lengyelország",
        "Czech Republic" to "Csehország",
        "Czechia" to "Csehország",
        "Austria" to "Ausztria",
        "Switzerland" to "Svájc",
        "Croatia" to "Horvátország",
        "Serbia" to "Szerbia",
        "Greece" to "Görögország",
        "Scotland" to "Skócia",
        "Denmark" to "Dánia",
        "Sweden" to "Svédország",
        "Norway" to "Norvégia",
        "Ukraine" to "Ukrajna",
        "Russia" to "Oroszország",
        "Romania" to "Románia",
        "Bulgaria" to "Bulgária",
        "Slovakia" to "Szlovákia",
        "Slovenia" to "Szlovénia",
        "Bosnia and Herzegovina" to "Bosznia-Hercegovina",
        "Bosnia" to "Bosznia-Hercegovina",
        "North Macedonia" to "Észak-Macedónia",
        "Macedonia" to "Észak-Macedónia",
        "Albania" to "Albánia",
        "Montenegro" to "Montenegró",
        "Kosovo" to "Koszovó",
        "Finland" to "Finnország",
        "Iceland" to "Izland",
        "Ireland" to "Írország",
        "Northern Ireland" to "Észak-Írország",
        "Wales" to "Wales",
        "Belarus" to "Fehéroroszország",
        "Moldova" to "Moldova",
        "Lithuania" to "Litvánia",
        "Latvia" to "Lettország",
        "Estonia" to "Észtország",
        "Luxembourg" to "Luxemburg",
        "Malta" to "Málta",
        "Cyprus" to "Ciprus",
        "Georgia" to "Grúzia",
        "Armenia" to "Örményország",
        "Azerbaijan" to "Azerbajdzsán",
        "Andorra" to "Andorra",
        "San Marino" to "San Marino",
        "Liechtenstein" to "Liechtenstein",
        "Faroe Islands" to "Feröer-szigetek",
        "Gibraltar" to "Gibraltár",

        // Ázsia
        "Japan" to "Japán",
        "South Korea" to "Dél-Korea",
        "Korea Republic" to "Dél-Korea",
        "North Korea" to "Észak-Korea",
        "China" to "Kína",
        "India" to "India",
        "Iran" to "Irán",
        "Iraq" to "Irak",
        "Saudi Arabia" to "Szaúd-Arábia",
        "UAE" to "Egyesült Arab Emírségek",
        "United Arab Emirates" to "Egyesült Arab Emírségek",
        "Qatar" to "Katar",
        "Kuwait" to "Kuvait",
        "Bahrain" to "Bahrein",
        "Oman" to "Omán",
        "Yemen" to "Jemen",
        "Jordan" to "Jordánia",
        "Lebanon" to "Libanon",
        "Syria" to "Szíria",
        "Israel" to "Izrael",
        "Palestine" to "Palesztina",
        "Vietnam" to "Vietnám",
        "Thailand" to "Thaiföld",
        "Indonesia" to "Indonézia",
        "Malaysia" to "Malajzia",
        "Singapore" to "Szingapúr",
        "Philippines" to "Fülöp-szigetek",
        "Myanmar" to "Mianmar",
        "Cambodia" to "Kambodzsa",
        "Laos" to "Laosz",
        "Uzbekistan" to "Üzbegisztán",
        "Kazakhstan" to "Kazahsztán",
        "Kyrgyzstan" to "Kirgizisztán",
        "Tajikistan" to "Tádzsikisztán",
        "Turkmenistan" to "Türkmenisztán",
        "Afghanistan" to "Afganisztán",
        "Pakistan" to "Pakisztán",
        "Bangladesh" to "Banglades",
        "Sri Lanka" to "Srí Lanka",
        "Nepal" to "Nepál",
        "Bhutan" to "Bhután",
        "Mongolia" to "Mongólia",
        "Hong Kong" to "Hongkong",
        "Taiwan" to "Tajvan",
        "Macau" to "Makaó",

        // Afrika
        "Egypt" to "Egyiptom",
        "Morocco" to "Marokkó",
        "Algeria" to "Algéria",
        "Tunisia" to "Tunézia",
        "Libya" to "Líbia",
        "South Africa" to "Dél-Afrika",
        "Nigeria" to "Nigéria",
        "Ghana" to "Ghána",
        "Cameroon" to "Kamerun",
        "Senegal" to "Szenegál",
        "Ivory Coast" to "Elefántcsontpart",
        "Cote d'Ivoire" to "Elefántcsontpart",
        "Mali" to "Mali",
        "Burkina Faso" to "Burkina Faso",
        "Guinea" to "Guinea",
        "Congo" to "Kongó",
        "DR Congo" to "Kongói DK",
        "Democratic Republic of the Congo" to "Kongói DK",
        "Angola" to "Angola",
        "Mozambique" to "Mozambik",
        "Zambia" to "Zambia",
        "Zimbabwe" to "Zimbabwe",
        "Kenya" to "Kenya",
        "Uganda" to "Uganda",
        "Tanzania" to "Tanzánia",
        "Ethiopia" to "Etiópia",
        "Sudan" to "Szudán",
        "Rwanda" to "Ruanda",
        "Gabon" to "Gabon",
        "Benin" to "Benin",
        "Togo" to "Togo",
        "Niger" to "Niger",
        "Chad" to "Csád",
        "Mauritania" to "Mauritánia",
        "Namibia" to "Namíbia",
        "Botswana" to "Botswana",
        "Madagascar" to "Madagaszkár",

        // Észak- és Közép-Amerika
        "USA" to "USA",
        "United States" to "USA",
        "Canada" to "Kanada",
        "Mexico" to "Mexikó",
        "Costa Rica" to "Costa Rica",
        "Panama" to "Panama",
        "Honduras" to "Honduras",
        "El Salvador" to "Salvador",
        "Guatemala" to "Guatemala",
        "Nicaragua" to "Nicaragua",
        "Jamaica" to "Jamaica",
        "Trinidad and Tobago" to "Trinidad és Tobago",
        "Haiti" to "Haiti",
        "Cuba" to "Kuba",
        "Dominican Republic" to "Dominikai Köztársaság",

        // Dél-Amerika
        "Brazil" to "Brazília",
        "Argentina" to "Argentína",
        "Uruguay" to "Uruguay",
        "Paraguay" to "Paraguay",
        "Chile" to "Chile",
        "Colombia" to "Kolumbia",
        "Peru" to "Peru",
        "Ecuador" to "Ecuador",
        "Bolivia" to "Bolívia",
        "Venezuela" to "Venezuela",

        // Óceánia
        "Australia" to "Ausztrália",
        "New Zealand" to "Új-Zéland",
        "Fiji" to "Fidzsi",
        "Papua New Guinea" to "Pápua Új-Guinea",

        // Egyéb
        "World" to "Világ",
        "Europe" to "Európa",
        "South America" to "Dél-Amerika",
        "North America" to "Észak-Amerika",
        "Africa" to "Afrika",
        "Asia" to "Ázsia",
        "Oceania" to "Óceánia",
        "International" to "Nemzetközi"
    )

    private val leagueMap = mapOf(
        // Top európai
        "Premier League" to "Premier League",
        "La Liga" to "La Liga",
        "LaLiga" to "La Liga",
        "Serie A" to "Serie A",
        "Bundesliga" to "Bundesliga",
        "Ligue 1" to "Ligue 1",
        "Eredivisie" to "Eredivisie",
        "Primeira Liga" to "Primeira Liga",
        "Liga Portugal" to "Liga Portugal",
        "Süper Lig" to "Süper Lig",
        "Championship" to "Championship",
        "2. Bundesliga" to "2. Bundesliga",
        "Serie B" to "Serie B",
        "La Liga 2" to "La Liga 2",
        "Ligue 2" to "Ligue 2",
        "Eerste Divisie" to "Eerste Divisie",

        // Magyar
        "NB I" to "NB I",
        "OTP Bank Liga" to "NB I",
        "NB II" to "NB II",
        "Magyar Kupa" to "Magyar Kupa",
        "Merkantil Bank Liga" to "NB II",

        // Nemzetközi kupák
        "UEFA Champions League" to "Bajnokok Ligája",
        "Champions League" to "Bajnokok Ligája",
        "UEFA Europa League" to "Európa-liga",
        "Europa League" to "Európa-liga",
        "UEFA Conference League" to "Konferencia Liga",
        "Conference League" to "Konferencia Liga",
        "FIFA Club World Cup" to "Klubvilágbajnokság",
        "World Cup" to "Világbajnokság",
        "European Championship" to "Európa-bajnokság",
        "Euro" to "Eb",
        "Copa America" to "Copa América",
        "Africa Cup of Nations" to "Afrikai Nemzetek Kupája",
        "Asian Cup" to "Ázsia-kupa",
        "Gold Cup" to "CONCACAF Aranykupa",
        "Nations League" to "Nemzetek Ligája",

        // Dél-Amerika
        "Copa Libertadores" to "Copa Libertadores",
        "Copa Sudamericana" to "Copa Sudamericana",
        "Brasileirão" to "Brazil bajnokság",
        "Serie A Brazil" to "Brazil Serie A",
        "Copa do Brasil" to "Brazil Kupa",
        "Copa do Brasil U20" to "Brazil Kupa U20",
        "Primera División" to "Primera División",
        "Primera División Argentina" to "Argentin Primera",
        "Liga Profesional" to "Liga Profesional",
        "Copa de la División Profesional" to "Bolíviai Profi Kupa",
        "Segunda División" to "Segunda División",
        "Primera B" to "Primera B",

        // Ázsia / Afrika
        "Botola Pro" to "Botola Pro",
        "Egyptian Premier League" to "Egyiptomi Premier League",
        "Saudi Pro League" to "Szaúdi Pro League",
        "AFC Champions League" to "AFC Bajnokok Ligája",
        "ASEAN Club Championship" to "ASEAN Klubbajnokság",
        "J1 League" to "J1 League",
        "K League 1" to "K League 1",
        "Chinese Super League" to "Kínai Szuperliga",
        "Indian Super League" to "Indiai Super League",
        "Persian Gulf Pro League" to "Perzsa-öböl Pro League",
        "Iraqi League" to "Iraki Liga",
        "Stars League" to "Stars League",
        "V.League 1" to "V.League 1",
        "Pro League A" to "Pro League A",
        "League Cup" to "Ligakupa",
        "Premier Soccer League" to "Premier Soccer League",
        "Ligue 1 Algeria" to "Ligue 1",
        "First League" to "Első liga",
        "Premier Division" to "Premier Division",
        "Division 1" to "Division 1",
        "IFA Shield" to "IFA Shield",
        "Veikkausliiga" to "Veikkausliiga",
        "Birinci Dəstə" to "Azerbajdzsán 1. liga",
        "Liga I" to "Román Liga I",
        "Liga Alef" to "Izraeli Liga Alef",
        "Cup" to "Kupa",
        "Friendlies" to "Barátságos",
        "Friendlies Women" to "Női barátságos",
        "League" to "Liga"
    )

    fun translateCountry(name: String?): String {
        if (name.isNullOrBlank()) return ""
        return countryMap[name.trim()] ?: name.trim()
    }

    fun translateLeague(name: String?): String {
        if (name.isNullOrBlank()) return "Egyéb"
        val trimmed = name.trim()
        return leagueMap[trimmed] ?: trimmed
    }

    fun formatHeader(country: String?, league: String?): String {
        val c = translateCountry(country)
        val l = translateLeague(league)
        return if (c.isNotBlank()) {
            "${c.uppercase()}: $l"
        } else {
            l.uppercase()
        }
    }
}
